import { ENUM_LOCATION_TYPE } from '@src/shared/enums/common.enums';

export const LOCATION_TYPE_HIERARCHY: Record<ENUM_LOCATION_TYPE, ENUM_LOCATION_TYPE | null> = {
  [ENUM_LOCATION_TYPE.DIVISION]: ENUM_LOCATION_TYPE.COUNTRY,
  [ENUM_LOCATION_TYPE.DISTRICT]: ENUM_LOCATION_TYPE.DIVISION,
  [ENUM_LOCATION_TYPE.UPAZILLA]: ENUM_LOCATION_TYPE.DISTRICT,
  [ENUM_LOCATION_TYPE.UNION]: ENUM_LOCATION_TYPE.UPAZILLA,
  [ENUM_LOCATION_TYPE.CITY_CORPORATION]: ENUM_LOCATION_TYPE.UPAZILLA,
  [ENUM_LOCATION_TYPE.POUROSOVA]: ENUM_LOCATION_TYPE.UPAZILLA,
  [ENUM_LOCATION_TYPE.COUNTRY]: ENUM_LOCATION_TYPE.COUNTRY
};
