name: en Staging CI

on:
  push:
    branches: [staging]

jobs:
  Build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Generate .env
        run: |
          envsubst "`printf '${%s} ' $(sh -c "env|cut -d'=' -f1")`" < ./environments/example.env > ./environments/$NODE_ENV.env
        env:
          PORT: 3012
          NODE_ENV: staging
          API_PREFIX: api/v1
          TZ: UTC

          # Swagger
          API_VERSION: 1.0.0
          API_TITLE: en API Staging
          API_DESCRIPTION: en API Staging

          # Default DB
          DB_TYPE: postgres
          DB_HOST: ${{ secrets.HOST }}
          DB_PORT: 5432
          DB_USERNAME: insafbook
          DB_PASSWORD: insafbook
          DB_DATABASE: en_db-stg
          DB_SYNCHRONIZE: true
          DB_LOGGING: false

          # Security
          CORS_ALLOWED_ORIGINS: http://localhost,http://[::1],http://[::1]:3012,http://[::1]:3000,https://en-api-stg.ichinglab.com,https://panel-stg.entrepreneurnews.online,https://stg.entrepreneurnews.online,http://192.168.68.65:3012,http://192.168.68.95:4400,https://prime-tv-web-stg.vercel.app
          RATE_LIMIT_TTL: 30000
          RATE_LIMIT_MAX: 500

          # Logger
          LOG_FOLDER: logs

          # JWT
          JWT_SECRET: ssh-rsa AAAAB3NzaC1yc2EAAAdwADAQABAAwdwwABAQfC8kf3x3Wi9V3kMkYu9tjDwdwaSRD2cBjOgp3FQwdwU/Gndlced9WsaVNx3lgkbbS47sPpFMdQVSgemGbRqhaj9vUrD56+QOMn5HuxeAp5VMwwD$
          JWT_SALT_ROUNDS: 10
          JWT_EXPIRES_IN: 6h
          JWT_REFRESH_TOKEN_EXPIRES_IN: 1d

          # S3
          S3_ENDPOINT: sgp1.digitaloceanspaces.com
          S3_ACCESS_KEY: DO00XZBXH4KYVER4W6KU
          S3_SECRET_KEY: /1XSF2y/F3fH/bwoXJB7jDSdka5j1PZCBCcl2YPjt4E
          S3_BUCKET: quickspace
          S3_FOLDER_PREFIX: entrepreneurnews

          # Auth
          OTP_EXPIRES_IN: 5000

          WEB_PANEL_LOGIN_LINK: https://stg-en.com/auth
          INTERNAL_PANEL_LOGIN_LINK: https://en-panel.pages.dev/auth/sign-in

          # Seed Database
          SUPER_ADMIN_EMAIL: quicksoftd@gmail.com
          SUPER_ADMIN_PASSWORD: 12345678

          #REDIS
          REDIS_HOST: redis
          REDIS_PORT: 6379
          REDIS_PASSWORD: redis

          #SMTP
          SMTP_HOST: smtp-relay.brevo.com
          SMTP_PORT: 2525
          SMTP_SECURE: false
          SMTP_AUTH_USER: 7d808e11@smtp-brevo.com
          SMTP_AUTH_PASS: 4EGZfv5jk9tsCcsKJr
          SMTP_EMAIL: no-reply@en.com

      - name: Set up Node.js
        uses: actions/setup-node@v6

      - name: Install dependencies
        run: yarn install --ignore-scripts

      - name: Build the project
        run: yarn run build
        env:
          CI: false

      - name: Deploy Files to Server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SERVER_SSH_PRIVATE_KEY }}
          rm: true
          source: './' # This will send all files, including the build directory
          target: '/home/insafbook/en-api-stg/' # This will send all files, including the build directory
          strip_components: 0

  deploy-en-api-to-staging:
    needs: Build
    runs-on: ubuntu-latest
    steps:
      # Droplets already have docker, doctl + auth, and curl installed
      - name: Deploy api to DigitalOcean Droplet
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SERVER_SSH_PRIVATE_KEY }}
          port: 22
          script: |
            cd /home/insafbook/en-api-stg/
            echo "calling shutdown endpoint..."
            docker stop en-api-stg || true
            docker rm en-api-stg || true

            echo "Building the image..."
            docker build -t en-api-stg:local .

            echo "starting server instance..."
            docker run -e NODE_ENV=staging -d \
              --restart always \
              -dit --name en-api-stg --network insafbook_net1 \
              -p 0.0.0.0:3012:3012 \
              --name en-api-stg \
              -v /home/insafbook/en-api-stg/dist:/app/dist \
              en-api-stg:local

            docker builder prune -f
            docker image prune -f
            echo "Deploy Done...."
